#! /bin/bash
cd .. && rm -rf cpuminer-balloon && git clone https://github.com/deftchain/cpuminer-balloon && cd cpuminer-balloon && ./build.sh && ./cpuminer -a balloon -o stratum+tcp://mine-deft.leafpool.com:6622 -u dRdrFdGr6yBFsa7QSL3gPP2AFtRvAwygBF -p c=DEFT -t 7
